### PR TITLE
Use rust-bindgen to generate FFI bindings

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by tamird** [comment]
@ebfull ping?

**Comment by Trolldemorted** [comment]
Why would you want to reparse the headers with every build?

Won't this break builds on windows? Winpcap and npcap installations don't come with their headers.

**Comment by tamird** [comment]
@Trolldemorted good point, and sorry for the delay. Updated this to include a script that regenerates the bindings, but the generated file is also included in the repo.

**Comment by Wojtek242** [comment]
This PR is not compatible with the newest version of `pcap`. If you would like to have it included, please update and resubmit.

**Pull request closed without merging**
