### PR TITLE
Offline filters

### PR DESCRIPTION
**Pull request by polachok**
This commit adds support for compiling filters into BPF programs and offline filtering.

### CODE REVIEW

**Comment by polachok** [comment]
@ebfull ping?

**Comment by ebfull** [comment]
@polachok Sorry that I haven't had time to review this! Reviewing now.

**Comment by ebfull** [comment]
Hm, I don't want to expose anything in `raw` in the public API if possible, so I'd rather have a wrapper type. And I need to double-check that the Clone impl is memory-safe.

**Comment by polachok** [comment]
Thanks for reviewing!

I don't quite follow, I think I only expose wrapper types (raw fields are not pub):

https://github.com/ebfull/pcap/pull/56/files#diff-b4aea3e418ccdb71239b96952d9cddb6R796

**Comment by ebfull** [comment]
Ah, sorry. I misread.

**Comment by aldanor** [comment]
Hi @polachok, wondering if this PR is still relevant? If so, it needs some tests (and a rebase on the latest master).

**Comment by polachok** [comment]
Yes, it's still relevant, we're using it in https://github.com/LTD-Beget/syncookied. What kind of tests do you need?

**Comment by bvandersloot** [comment]
Just commenting as another party that thinks this is a very useful feature. I'm running my project off of @polachok's branch until this is merged.

**Comment by ebfull** [comment]
My next priority is to review and merge this.

**Pull request merged**
