### PR TITLE
Add stats (received/dropped packets) to Capture

### PR DESCRIPTION
**Pull request by lrbalt**
This PR implements a stats fn in Capture. It uses pcap_stats. An example is added to show its use.

### CODE REVIEW

**Comment by ebfull** [comment]
Cool! Can you also make `Stat` impl `Copy`/`Clone` as well?

**Comment by lrbalt** [comment]
sure. You mean `impl Clone for Stat` right? or do you mean adding `#[derive(Copy, Clone)]`
(I'm new to Rust)

**Comment by ebfull** [comment]
That's perfect. Thanks!

**Comment by lrbalt** [comment]
thanks for merging :-)

**Comment by ebfull** [comment]
I finally pushed a new version which includes this, my apologies.

**Comment by lrbalt** [comment]
no problem! Thanks

**Pull request merged**
