### PR TITLE
All the toolchains!

### PR DESCRIPTION
**Pull request by Trolldemorted**
https://github.com/ebfull/pcap/issues/119 is not a nightly issue, so let's test all the things!

### CODE REVIEW

**Comment by sekineh** [comment]
CI is not free resource and we must pick the most relevant/efficient combination.
If I calculate correctly we can only perform 2000 / 100 = 20 runs of CI build / month in this setting.
We should use resource for more features, not release channels.

## Calculation

From 18 jobs, cpu time are roughly calculated like below:
- windows: 3.5 + 3.5 + 4.5 + 3.5 + 3.5 + 4.5 = 23 min (x2)
- ubuntu: ~5 min?
- macos: ~5 min? (x10)

windows and macos runner are expensive.
Total cpu time calculated is 23 x 2 + 5 + 5 x 10 = 101 min
Free tier limit is 2000 min / month. I think it's per user.

Reference:
- https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by Trolldemorted** [comment]
>CI is not free resource

If github actions *really* does not grant unlimited build minutes to open source repos then I can set up CI with azure pipelines - they definitely have unlimited minutes for everything open source. It's 2020, CI is a free resource if your software is open source and you have the right provider ¯\\_(ツ)_/¯

Are you sure the 2k limit is applied to public repos? The billig page explicitly says 2k quote is for private repos, and I have accumulated nothing with my usage in open source organizations:
grafik

**Comment by sekineh** [comment]
Hmm, you are totally right. I found the following sentence from URL I pasted.

> GitHub Actions usage is free for public repositories. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account.

**Review by sekineh — APPROVED** [review]
Thanks for explanation, let's merge it!

**Pull request merged**
