### PR TITLE
Streaming

### PR DESCRIPTION
**Pull request by stephanbuys**
Based on the @Roxxik's referenced in #71.

### CODE REVIEW

**Comment by stephanbuys** [comment]
@ebfull as requested, you will just need to run tests with --features tokio for it to compile though, please let me know any fixes I can do.

**Comment by ebfull** [comment]
I am super busy but I'm excited to review this patch. I will do so while I'm out of town next week. I apologize for the delay.

**Comment by Roxxik** [comment]
seems like examples/streamlisten.rs hasn't listed futures as dependency (for rustc stable and beta at least)

**Comment by ebfull** [comment]
Awesome! No complaints on my end.

**Pull request merged**
